### ISSUE TITLE
SSO Authentication & Usage Management Implementation 

### ISSUE THREAD

**Issue by mattlawlis** [OpenAssistantGPT/chatbot-sdk#146]
### Feature Description

Hi Olivier, 

Would love to see the addition of your new SSO/SAML Authentication that you've added to OpenAssistantGPT and also the Usage Management feature to the SDK. Is this on the pipeline?

### Use Case

- Authentication of users 
- Prevent users from using too many resources

**Comment by marcolivierbouch** [comment]
Hello this is our enterprise features we don't share all the code of those features. But I can share how we make it work.

We use NextAuth.js with SSOReady https://ssoready.com/ before using our sdk on the server side we validate that you are connected.
